ServerEvents.recipes(event => {

event.remove({ mod: 'alekiships' }),
event.remove({ mod: 'tacz' }),
event.remove({ mod: 'immersive_melodies' }),
event.remove({ mod: 'manyideas_core'}),
event.remove({ mod: "manyideas_doors"}),
event.remove({ mod: 'immersiveengineering'}),
event.remove({ mod: 'advancedtfctech'}),
event.remove({ mod: 'immersivepetroleum'}),
event.remove({ output: 'tfc_metallurgy:metal/ingot/aluminum' }),
event.remove({ output: 'tfc_items:arrow_fletch' }),
event.remove({ output: 'tfc_items:arrow_shaft' }),
event.remove({ output: 'tfc_items:arrow_tread' }),
event.remove({ output: 'immersiveengineering:rs_engineering' }),
event.remove({ output: 'epic_knights_ores_and_alloys:steel_block' }),
event.remove({ output: 'immersiveengineering:drill' }),
event.remove({ output: 'immersiveengineering:gunpart_barrel' }),
event.remove({ output: 'immersiveengineering:gunpart_drum' }),
event.remove({ output: 'immersiveengineering:gunpart_hammer' }),
event.remove({ output: 'immersiveengineering:revolver' }),
event.remove({ output: 'immersiveengineering:speedloader' }),
event.remove({ output: 'immersiveengineering:toolupgrade_revolver_bayonet' }),
event.remove({ output: 'immersiveengineering:toolupgrade_revolver_magazine' }),
event.remove({ output: 'immersiveengineering:toolupgrade_revolver_electro' }),
event.remove({ output: 'immersiveengineering:toolupgrade_buzzsaw_spareblades' }),
event.remove({ output: 'immersiveengineering:buzzsaw' }),
event.remove({ output: 'immersiveengineering:rockcutter'  }),
event.remove({ output: 'immersiveengineering:sawblade' }),
event.remove({ output: 'immersiveengineering:toolupgrade_powerpack_magnet' }),
event.remove({ output: 'immersiveengineering:toolupgrade_powerpack_tesla' }),
event.remove({ output: 'immersiveengineering:tesla_coil' }),
event.remove({ output: 'immersiveengineering:toolupgrade_powerpack_induction' }),
event.remove({ output: 'immersiveengineering:toolupgrade_powerpack_antenna' }),
event.remove({ output: 'immersiveengineering:shield' }),
event.remove({ output: 'immersiveengineering:toolupgrade_shield_magnet' }),
event.remove({ output: 'immersiveengineering:sample_drill' }),
event.remove({ output: 'immersiveengineering:survey_tools' }),
event.remove({ output: 'immersiveengineering:skyhook' }),
event.remove({ output: 'immersiveengineering:drillhead_steel' }),
event.remove({ output: 'immersiveengineering:drillhead_iron' }),
event.remove({ output: 'immersiveengineering:toolupgrade_drill_waterproof' }),
event.remove({ output: 'immersiveengineering:toolupgrade_drill_lube' }),
event.remove({ output: 'immersiveengineering:toolupgrade_drill_damage' }),
event.remove({ output: 'immersiveengineering:toolupgrade_drill_capacity' }),
event.remove({ output: 'tfc_ie_addon:drillhead_black_steel' }),
event.remove({ output: 'tfc_ie_addon:drillhead_blue_steel' }),
event.remove({ output: 'tfc_ie_addon:drillhead_red_steel' }),
event.remove({ output: 'immersiveengineering:chemthrower' }),
event.remove({ output: 'immersiveengineering:toolupgrade_railgun_scope' }),
event.remove({ output: 'immersiveengineering:railgun' }),
event.remove({ output: 'immersiveengineering:toolupgrade_railgun_capacitors' }),
event.remove({ output: 'immersiveengineering:homing' }),
event.remove({ output: 'immersiveengineering:casull' }),
event.remove({ output: 'immersiveengineering:armor_piercing' }),
event.remove({ output: 'immersiveengineering:buckshot' }),
event.remove({ output: 'immersiveengineering:he' }),
event.remove({ output: 'immersiveengineering:glider' }),
event.remove({ output: 'immersiveengineering:turret_chem' }),
event.remove({ output: 'immersiveengineering:cloche' }),
event.remove({ output: 'immersiveengineering:turret_gun' }),
event.remove({ output: 'immersiveengineering:powerpack' }),
event.remove({ output: 'immersiveengineering:wolfpack' }),
event.remove({ output: 'immersiveengineering:potion' }),
event.remove({ output: 'immersiveengineering:dragons_breath' }),
event.remove({ output: 'immersiveengineering:silver' }),
event.remove({ output: 'immersiveengineering:flare' }),
event.remove({ output: 'immersiveengineering:firework' }),
event.remove({ output: 'immersiveengineering:toolupgrade_chemthrower_focus' }),
event.remove({ output: 'immersiveengineering:toolupgrade_chemthrower_multitank' }),
event.remove({ output: 'immersiveengineering:hammer' }),
event.remove({ output: 'immersiveengineering:empty_shell' }),
event.remove({ output: 'immersiveengineering:empty_casing' }),
event.remove({ output: 'shoppy:shop_block'}),
event.remove({ output: 'shoppy:bartering_station'})
event.remove({output: 'immersiveengineering:nugget_lead'})
})